### PR TITLE
Fix grid calcs

### LINKED ISSUE #542: XYFrame Heatmap:  Certain chart size & bin combinations result in an extra bin.
I have the following code:

```
const testData = [
      {
        coordinates: [
          { x: 0, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 0, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 10, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 10, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 20, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 20, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 30, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 30, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 40, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 40, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 50, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 50, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 60, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 60, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 70, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 70, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 80, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 80, y: 90, count: Math.ceil(Math.random() * 100) },

          { x: 90, y: 0, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 10, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 20, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 30, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 40, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 50, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 60, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 70, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 80, count: Math.ceil(Math.random() * 100) },
          { x: 90, y: 90, count: Math.ceil(Math.random() * 100) },
        ],
      },
    ]

    const maxCount = Math.max(...clusterHeatmapData[0].coordinates.map((c: any) => c.count))

    const color = scaleLinear<string>().domain([0, maxCount]).range(['cadetblue', 'tomato'])

    const frameProps = {
      summaries: testData,
      size: [276, 276],
      margin: { left: 10, bottom: 10, right: 10, top: 10 },
      summaryType: {
        type: 'heatmap',
        xBins: 10,
        yBins: 10,
        binValue: (d: any) => d.count,
      },
      xAccessor: 'x',
      yAccessor: 'y',
      yExtent: [0],
      xExtent: [0],
      summaryStyle: function (e: any) {
        return {
          fill: e.binItems[0] && color(e.binItems[0].count),
          stroke: '#ccc',
          strokeWidth: 0.5,
        }
      },
    }
    return <XYFrame {...frameProps} />

```

The data is 10 x 10. BinX & binY are set to 10 bins. For some reason there are extra binY and binX generated: 

image

If I change the size slightly to , let's say, `size = [268, 268]`, the chart is as expected: 

image

My guess is javascript floating point is the culprit.

### PR DESCRIPTION
**Pull request by emeeks**
Closes #542 (edited to autoclose bug issue).

The `heatmap` option in `XYFrame` had a couple fundamental issues with how cells were being calculated, including an embarrassing typo. This should fix them.

### CODE REVIEW

File: src/components/svg/areaDrawing.tsx [hunk 1]
```diff
@@ -437,7 +438,7 @@ export function heatmapping({
 
     heatmapData._xyfCoordinates.forEach((d: [number, number], di: number) => {
       const baseX = heatmapBinXScale(d[0]) as number
-      const baseY = heatmapBinXScale(d[1]) as number
+      const baseY = heatmapBinYScale(d[1]) as number
```
Comment (willingc) [inline src/components/svg/areaDrawing.tsx:441]: Oops.

**Review by willingc — APPROVED** [review]
LGTM.
